function [IndexLeft,IndexRight,QsInvA,QsInvB,QdotsInvA...
    ,QdotsInvB,orderQsOpp] = GetIndexHelper(S,IO)
%UNTITLED5 Summary of this function goes here
%   Detailed explanation goes here

if strcmp(S.ModelName,'Rajagopal')
    % indexes to select kinematics left and right leg
    IndexLeft = IO.jointi.leg_l;
    IndexRight = IO.jointi.leg_r;
elseif strcmp(S.ModelName,'Gait92')
    % indexes to select kinematics left and right leg
    IndexLeft = [IO.jointi.leg_l IO.jointi.trunki];
    IndexRight = [IO.jointi.leg_r IO.jointi.trunki];
end

% indexes for symmetry steps
QsInvA = [IO.coordi.pelvis_tilt,...
    IO.coordi.pelvis_ty,...
    IO.jointi.leg_r,IO.jointi.leg_l,...
    IO.coordi.lumbar_extension,...
    IO.jointi.arm_r,IO.jointi.arm_l]';
QsInvB = [jointi.pelvis.tilt,...
    jointi.pelvis.ty,...
    IO.jointi.leg_l,IO.jointi.leg_r,...
    IO.coordi.lumbar_extension,...
    IO.jointi.arm_l,IO.jointi.arm_r]';

QdotsInvA = [IO.coordi.pelvis_tilt,...
    IO.coordi.pelvis_tx,IO.coordi.pelvis_ty,...
    IO.jointi.leg_r,IO.jointi.leg_l,...
    IO.coordi.lumbar_extension,...
    IO.jointi.arm_r,IO.jointi.arm_l]';
QdotsInvB = [jointi.pelvis.tilt,...
    IO.coordi.pelvis_tx,IO.coordi.pelvis_ty,...
    IO.jointi.leg_l,IO.jointi.leg_r,...
    IO.coordi.lumbar_extension,...
    IO.jointi.arm_l,IO.jointi.arm_r]';

orderQsOpp = [IO.coordi.pelvis_list:IO.coordi.pelvis_list,...
    IO.coordi.pelvis_rot:IO.coordi.pelvis_rot,...
    IO.coordi.pelvis_tz:IO.coordi.pelvis_tz,...
    IO.coordi.lumbar_bending:IO.coordi.lumbar_bending,...
    IO.coordi.lumbar_rotation:IO.coordi.lumbar_rotation];

end

