function [Tau_passk_opt,Tau_passk_opt_all] = GetPassiveMoments(f_PassiveMoments,f_passiveTATorques,...
    k_pass,theta,q_opt_unsc_all,qdot_opt_unsc_all,stiffnessArm,dampingArm,N,nq)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here


Tau_passk_opt_all = zeros(N,nq.all-nq.abs);
for i = 1:N
    Tau_passk_opt.hip.flex.l = full(f_PassiveMoments(k_pass.hip.flex,...
        theta.pass.hip.flex,q_opt_unsc_all.rad(i+1,jointi.hip_flex.l),...
        qdot_opt_unsc_all.rad(i+1,jointi.hip_flex.l)));
    Tau_passk_opt.hip.flex.r = full(f_PassiveMoments(k_pass.hip.flex,...
        theta.pass.hip.flex,q_opt_unsc_all.rad(i+1,jointi.hip_flex.r),...
        qdot_opt_unsc_all.rad(i+1,jointi.hip_flex.r)));
    Tau_passk_opt.hip.add.l = full(f_PassiveMoments(k_pass.hip.add,...
        theta.pass.hip.add,q_opt_unsc_all.rad(i+1,jointi.hip_add.l),...
        qdot_opt_unsc_all.rad(i+1,jointi.hip_add.l)));
    Tau_passk_opt.hip.add.r = full(f_PassiveMoments(k_pass.hip.add,...
        theta.pass.hip.add,q_opt_unsc_all.rad(i+1,jointi.hip_add.r),...
        qdot_opt_unsc_all.rad(i+1,jointi.hip_add.r)));
    Tau_passk_opt.hip.rot.l = full(f_PassiveMoments(k_pass.hip.rot,...
        theta.pass.hip.rot,q_opt_unsc_all.rad(i+1,jointi.hip_rot.l),...
        qdot_opt_unsc_all.rad(i+1,jointi.hip_rot.l)));
    Tau_passk_opt.hip.rot.r = full(f_PassiveMoments(k_pass.hip.rot,...
        theta.pass.hip.rot,q_opt_unsc_all.rad(i+1,jointi.hip_rot.r),...
        qdot_opt_unsc_all.rad(i+1,jointi.hip_rot.r)));
    Tau_passk_opt.knee.l = full(f_PassiveMoments(k_pass.knee,...
        theta.pass.knee,q_opt_unsc_all.rad(i+1,jointi.knee.l),...
        qdot_opt_unsc_all.rad(i+1,jointi.knee.l)));
    Tau_passk_opt.knee.r = full(f_PassiveMoments(k_pass.knee,...
        theta.pass.knee,q_opt_unsc_all.rad(i+1,jointi.knee.r),...
        qdot_opt_unsc_all.rad(i+1,jointi.knee.r)));
    Tau_passk_opt.ankle.l = full(f_PassiveMoments(k_pass.ankle,...
        theta.pass.ankle,q_opt_unsc_all.rad(i+1,jointi.ankle.l),...
        qdot_opt_unsc_all.rad(i+1,jointi.ankle.l)));
    Tau_passk_opt.ankle.r = full(f_PassiveMoments(k_pass.ankle,...
        theta.pass.ankle,q_opt_unsc_all.rad(i+1,jointi.ankle.r),...
        qdot_opt_unsc_all.rad(i+1,jointi.ankle.r)));
    Tau_passk_opt.subt.l = full(f_PassiveMoments(k_pass.subt,...
        theta.pass.subt,q_opt_unsc_all.rad(i+1,jointi.subt.l),...
        qdot_opt_unsc_all.rad(i+1,jointi.subt.l)));
    Tau_passk_opt.subt.r = full(f_PassiveMoments(k_pass.subt,...
        theta.pass.subt,q_opt_unsc_all.rad(i+1,jointi.subt.r),...
        qdot_opt_unsc_all.rad(i+1,jointi.subt.r)));
    Tau_passk_opt.trunk.ext = full(f_PassiveMoments(k_pass.trunk.ext,...
        theta.pass.trunk.ext,q_opt_unsc_all.rad(i+1,jointi.trunk.ext),...
        qdot_opt_unsc_all.rad(i+1,jointi.trunk.ext)));
    Tau_passk_opt.trunk.ben = full(f_PassiveMoments(k_pass.trunk.ben,...
        theta.pass.trunk.ben,q_opt_unsc_all.rad(i+1,jointi.trunk.ben),...
        qdot_opt_unsc_all.rad(i+1,jointi.trunk.ben)));
    Tau_passk_opt.trunk.rot = full(f_PassiveMoments(k_pass.trunk.rot,...
        theta.pass.trunk.rot,q_opt_unsc_all.rad(i+1,jointi.trunk.rot),...
        qdot_opt_unsc_all.rad(i+1,jointi.trunk.rot)));
    
    Tau_passk_opt.sh_flex.l = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.sh_flex.l), qdot_opt_unsc_all.rad(i+1,jointi.sh_flex.l)));
    Tau_passk_opt.sh_add.l = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.sh_add.l), qdot_opt_unsc_all.rad(i+1,jointi.sh_add.l)));
    Tau_passk_opt.sh_rot.l = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.sh_rot.l), qdot_opt_unsc_all.rad(i+1,jointi.sh_rot.l)));
    Tau_passk_opt.sh_flex.r = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.sh_flex.r), qdot_opt_unsc_all.rad(i+1,jointi.sh_flex.r)));
    Tau_passk_opt.sh_add.r = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.sh_add.r), qdot_opt_unsc_all.rad(i+1,jointi.sh_add.r)));
    Tau_passk_opt.sh_rot.r = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.sh_rot.r), qdot_opt_unsc_all.rad(i+1,jointi.sh_rot.r)));
    Tau_passk_opt.elb.l = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.elb.l), qdot_opt_unsc_all.rad(i+1,jointi.elb.l)));
    Tau_passk_opt.elb.r = full(f_passiveTATorques(stiffnessArm, dampingArm, ...
        q_opt_unsc_all.rad(i+1,jointi.elb.r), qdot_opt_unsc_all.rad(i+1,jointi.elb.r)));
    Tau_passk_opt.arm(i,:) = [Tau_passk_opt.sh_flex.l, Tau_passk_opt.sh_add.l, ...
        Tau_passk_opt.sh_rot.l, Tau_passk_opt.sh_flex.r, Tau_passk_opt.sh_add.r, ...
        Tau_passk_opt.sh_rot.r, Tau_passk_opt.elb.l, Tau_passk_opt.elb.r];
    
    Tau_passk_opt.mtp.l = full(f_passiveTATorques(stiffnessMtp, dampingMtp, ...
        q_opt_unsc_all.rad(i+1,jointi.mtp.l), qdot_opt_unsc_all.rad(i+1,jointi.mtp.l)));
    Tau_passk_opt.mtp.r = full(f_passiveTATorques(stiffnessMtp, dampingMtp, ...
        q_opt_unsc_all.rad(i+1,jointi.mtp.r), qdot_opt_unsc_all.rad(i+1,jointi.mtp.r)));
    Tau_passk_opt.mtp.all(i,:) = [Tau_passk_opt.mtp.l, Tau_passk_opt.mtp.r];
    
    Tau_passk_opt_all(i,:) = [Tau_passk_opt.hip.flex.l,...
        Tau_passk_opt.hip.add.l,Tau_passk_opt.hip.rot.l,...
        Tau_passk_opt.hip.flex.r,Tau_passk_opt.hip.add.r,...
        Tau_passk_opt.hip.rot.r,Tau_passk_opt.knee.l,...
        Tau_passk_opt.knee.r,Tau_passk_opt.ankle.l,...
        Tau_passk_opt.ankle.r,Tau_passk_opt.subt.l,...
        Tau_passk_opt.subt.r,Tau_passk_opt.mtp.all(i,:),...
        Tau_passk_opt.trunk.ext,Tau_passk_opt.trunk.ben,...
        Tau_passk_opt.trunk.rot,Tau_passk_opt.arm(i,:),];
    
end



end

