name: Build Sphinx website
# Builds the website when a pull request is made. The website files 
# can be downloaded from the github actions tab to be reviewed locally.

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Documentation/requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build -M html Documentation/source/ Documentation/build/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Documentation/build/html'
